/**
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: unversioned
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { IoK8sApiCoreV1ResourceHealth } from '../models/IoK8sApiCoreV1ResourceHealth';
import { HttpFile } from '../http/http';

export class IoK8sApiCoreV1ResourceStatus {
    /**
    * Name of the resource. Must be unique within the pod and match one of the resources from the pod spec.
    */
    'name': string;
    /**
    * List of unique Resources health. Each element in the list contains an unique resource ID and resource health. At a minimum, ResourceID must uniquely identify the Resource allocated to the Pod on the Node for the lifetime of a Pod. See ResourceID type for it\'s definition.
    */
    'resources'?: Array<IoK8sApiCoreV1ResourceHealth>;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "name",
            "baseName": "name",
            "type": "string",
            "format": ""
        },
        {
            "name": "resources",
            "baseName": "resources",
            "type": "Array<IoK8sApiCoreV1ResourceHealth>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return IoK8sApiCoreV1ResourceStatus.attributeTypeMap;
    }

    public constructor() {
    }
}
