/**
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: unversioned
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { IoK8sApiFlowcontrolV1beta3GroupSubject } from '../models/IoK8sApiFlowcontrolV1beta3GroupSubject';
import { IoK8sApiFlowcontrolV1beta3ServiceAccountSubject } from '../models/IoK8sApiFlowcontrolV1beta3ServiceAccountSubject';
import { IoK8sApiFlowcontrolV1beta3UserSubject } from '../models/IoK8sApiFlowcontrolV1beta3UserSubject';
import { HttpFile } from '../http/http';

/**
* Subject matches the originator of a request, as identified by the request authentication system. There are three ways of matching an originator; by user, group, or service account.
*/
export class IoK8sApiFlowcontrolV1beta3Subject {
    'group'?: IoK8sApiFlowcontrolV1beta3GroupSubject;
    /**
    * `kind` indicates which one of the other fields is non-empty. Required
    */
    'kind': string;
    'serviceAccount'?: IoK8sApiFlowcontrolV1beta3ServiceAccountSubject;
    'user'?: IoK8sApiFlowcontrolV1beta3UserSubject;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "group",
            "baseName": "group",
            "type": "IoK8sApiFlowcontrolV1beta3GroupSubject",
            "format": ""
        },
        {
            "name": "kind",
            "baseName": "kind",
            "type": "string",
            "format": ""
        },
        {
            "name": "serviceAccount",
            "baseName": "serviceAccount",
            "type": "IoK8sApiFlowcontrolV1beta3ServiceAccountSubject",
            "format": ""
        },
        {
            "name": "user",
            "baseName": "user",
            "type": "IoK8sApiFlowcontrolV1beta3UserSubject",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return IoK8sApiFlowcontrolV1beta3Subject.attributeTypeMap;
    }

    public constructor() {
    }
}
