/**
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: unversioned
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { IoK8sApiBatchV1SuccessPolicyRule } from '../models/IoK8sApiBatchV1SuccessPolicyRule';
import { HttpFile } from '../http/http';

/**
* SuccessPolicy describes when a Job can be declared as succeeded based on the success of some indexes.
*/
export class IoK8sApiBatchV1SuccessPolicy {
    /**
    * rules represents the list of alternative rules for the declaring the Jobs as successful before `.status.succeeded >= .spec.completions`. Once any of the rules are met, the \"SucceededCriteriaMet\" condition is added, and the lingering pods are removed. The terminal state for such a Job has the \"Complete\" condition. Additionally, these rules are evaluated in order; Once the Job meets one of the rules, other rules are ignored. At most 20 elements are allowed.
    */
    'rules': Array<IoK8sApiBatchV1SuccessPolicyRule>;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "rules",
            "baseName": "rules",
            "type": "Array<IoK8sApiBatchV1SuccessPolicyRule>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return IoK8sApiBatchV1SuccessPolicy.attributeTypeMap;
    }

    public constructor() {
    }
}
