/**
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: unversioned
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { IoK8sApiResourceV1alpha3OpaqueDeviceConfiguration } from '../models/IoK8sApiResourceV1alpha3OpaqueDeviceConfiguration';
import { HttpFile } from '../http/http';

/**
* DeviceAllocationConfiguration gets embedded in an AllocationResult.
*/
export class IoK8sApiResourceV1alpha3DeviceAllocationConfiguration {
    'opaque'?: IoK8sApiResourceV1alpha3OpaqueDeviceConfiguration;
    /**
    * Requests lists the names of requests where the configuration applies. If empty, its applies to all requests.
    */
    'requests'?: Array<string>;
    /**
    * Source records whether the configuration comes from a class and thus is not something that a normal user would have been able to set or from a claim.
    */
    'source': string;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "opaque",
            "baseName": "opaque",
            "type": "IoK8sApiResourceV1alpha3OpaqueDeviceConfiguration",
            "format": ""
        },
        {
            "name": "requests",
            "baseName": "requests",
            "type": "Array<string>",
            "format": ""
        },
        {
            "name": "source",
            "baseName": "source",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return IoK8sApiResourceV1alpha3DeviceAllocationConfiguration.attributeTypeMap;
    }

    public constructor() {
    }
}
