/**
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: unversioned
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { IoK8sApiResourceV1alpha3DeviceClaim } from '../models/IoK8sApiResourceV1alpha3DeviceClaim';
import { HttpFile } from '../http/http';

/**
* ResourceClaimSpec defines what is being requested in a ResourceClaim and how to configure it.
*/
export class IoK8sApiResourceV1alpha3ResourceClaimSpec {
    /**
    * Controller is the name of the DRA driver that is meant to handle allocation of this claim. If empty, allocation is handled by the scheduler while scheduling a pod.  Must be a DNS subdomain and should end with a DNS domain owned by the vendor of the driver.  This is an alpha field and requires enabling the DRAControlPlaneController feature gate.
    */
    'controller'?: string;
    'devices'?: IoK8sApiResourceV1alpha3DeviceClaim;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "controller",
            "baseName": "controller",
            "type": "string",
            "format": ""
        },
        {
            "name": "devices",
            "baseName": "devices",
            "type": "IoK8sApiResourceV1alpha3DeviceClaim",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return IoK8sApiResourceV1alpha3ResourceClaimSpec.attributeTypeMap;
    }

    public constructor() {
    }
}
