/**
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: unversioned
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { IoK8sApiCoreV1ClusterTrustBundleProjection } from '../models/IoK8sApiCoreV1ClusterTrustBundleProjection';
import { IoK8sApiCoreV1ConfigMapProjection } from '../models/IoK8sApiCoreV1ConfigMapProjection';
import { IoK8sApiCoreV1DownwardAPIProjection } from '../models/IoK8sApiCoreV1DownwardAPIProjection';
import { IoK8sApiCoreV1SecretProjection } from '../models/IoK8sApiCoreV1SecretProjection';
import { IoK8sApiCoreV1ServiceAccountTokenProjection } from '../models/IoK8sApiCoreV1ServiceAccountTokenProjection';
import { HttpFile } from '../http/http';

/**
* Projection that may be projected along with other supported volume types. Exactly one of these fields must be set.
*/
export class IoK8sApiCoreV1VolumeProjection {
    'clusterTrustBundle'?: IoK8sApiCoreV1ClusterTrustBundleProjection;
    'configMap'?: IoK8sApiCoreV1ConfigMapProjection;
    'downwardAPI'?: IoK8sApiCoreV1DownwardAPIProjection;
    'secret'?: IoK8sApiCoreV1SecretProjection;
    'serviceAccountToken'?: IoK8sApiCoreV1ServiceAccountTokenProjection;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "clusterTrustBundle",
            "baseName": "clusterTrustBundle",
            "type": "IoK8sApiCoreV1ClusterTrustBundleProjection",
            "format": ""
        },
        {
            "name": "configMap",
            "baseName": "configMap",
            "type": "IoK8sApiCoreV1ConfigMapProjection",
            "format": ""
        },
        {
            "name": "downwardAPI",
            "baseName": "downwardAPI",
            "type": "IoK8sApiCoreV1DownwardAPIProjection",
            "format": ""
        },
        {
            "name": "secret",
            "baseName": "secret",
            "type": "IoK8sApiCoreV1SecretProjection",
            "format": ""
        },
        {
            "name": "serviceAccountToken",
            "baseName": "serviceAccountToken",
            "type": "IoK8sApiCoreV1ServiceAccountTokenProjection",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return IoK8sApiCoreV1VolumeProjection.attributeTypeMap;
    }

    public constructor() {
    }
}
