/**
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: unversioned
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { IoK8sApiCoreV1AttachedVolume } from '../models/IoK8sApiCoreV1AttachedVolume';
import { IoK8sApiCoreV1ContainerImage } from '../models/IoK8sApiCoreV1ContainerImage';
import { IoK8sApiCoreV1NodeAddress } from '../models/IoK8sApiCoreV1NodeAddress';
import { IoK8sApiCoreV1NodeCondition } from '../models/IoK8sApiCoreV1NodeCondition';
import { IoK8sApiCoreV1NodeConfigStatus } from '../models/IoK8sApiCoreV1NodeConfigStatus';
import { IoK8sApiCoreV1NodeDaemonEndpoints } from '../models/IoK8sApiCoreV1NodeDaemonEndpoints';
import { IoK8sApiCoreV1NodeFeatures } from '../models/IoK8sApiCoreV1NodeFeatures';
import { IoK8sApiCoreV1NodeRuntimeHandler } from '../models/IoK8sApiCoreV1NodeRuntimeHandler';
import { IoK8sApiCoreV1NodeSystemInfo } from '../models/IoK8sApiCoreV1NodeSystemInfo';
import { HttpFile } from '../http/http';

/**
* NodeStatus is information about the current status of a node.
*/
export class IoK8sApiCoreV1NodeStatus {
    /**
    * List of addresses reachable to the node. Queried from cloud provider, if available. More info: https://kubernetes.io/docs/concepts/nodes/node/#addresses Note: This field is declared as mergeable, but the merge key is not sufficiently unique, which can cause data corruption when it is merged. Callers should instead use a full-replacement patch. See https://pr.k8s.io/79391 for an example. Consumers should assume that addresses can change during the lifetime of a Node. However, there are some exceptions where this may not be possible, such as Pods that inherit a Node\'s address in its own status or consumers of the downward API (status.hostIP).
    */
    'addresses'?: Array<IoK8sApiCoreV1NodeAddress>;
    /**
    * Allocatable represents the resources of a node that are available for scheduling. Defaults to Capacity.
    */
    'allocatable'?: { [key: string]: string; };
    /**
    * Capacity represents the total resources of a node. More info: https://kubernetes.io/docs/reference/node/node-status/#capacity
    */
    'capacity'?: { [key: string]: string; };
    /**
    * Conditions is an array of current observed node conditions. More info: https://kubernetes.io/docs/concepts/nodes/node/#condition
    */
    'conditions'?: Array<IoK8sApiCoreV1NodeCondition>;
    'config'?: IoK8sApiCoreV1NodeConfigStatus;
    'daemonEndpoints'?: IoK8sApiCoreV1NodeDaemonEndpoints;
    'features'?: IoK8sApiCoreV1NodeFeatures;
    /**
    * List of container images on this node
    */
    'images'?: Array<IoK8sApiCoreV1ContainerImage>;
    'nodeInfo'?: IoK8sApiCoreV1NodeSystemInfo;
    /**
    * NodePhase is the recently observed lifecycle phase of the node. More info: https://kubernetes.io/docs/concepts/nodes/node/#phase The field is never populated, and now is deprecated.
    */
    'phase'?: string;
    /**
    * The available runtime handlers.
    */
    'runtimeHandlers'?: Array<IoK8sApiCoreV1NodeRuntimeHandler>;
    /**
    * List of volumes that are attached to the node.
    */
    'volumesAttached'?: Array<IoK8sApiCoreV1AttachedVolume>;
    /**
    * List of attachable volumes in use (mounted) by the node.
    */
    'volumesInUse'?: Array<string>;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "addresses",
            "baseName": "addresses",
            "type": "Array<IoK8sApiCoreV1NodeAddress>",
            "format": ""
        },
        {
            "name": "allocatable",
            "baseName": "allocatable",
            "type": "{ [key: string]: string; }",
            "format": ""
        },
        {
            "name": "capacity",
            "baseName": "capacity",
            "type": "{ [key: string]: string; }",
            "format": ""
        },
        {
            "name": "conditions",
            "baseName": "conditions",
            "type": "Array<IoK8sApiCoreV1NodeCondition>",
            "format": ""
        },
        {
            "name": "config",
            "baseName": "config",
            "type": "IoK8sApiCoreV1NodeConfigStatus",
            "format": ""
        },
        {
            "name": "daemonEndpoints",
            "baseName": "daemonEndpoints",
            "type": "IoK8sApiCoreV1NodeDaemonEndpoints",
            "format": ""
        },
        {
            "name": "features",
            "baseName": "features",
            "type": "IoK8sApiCoreV1NodeFeatures",
            "format": ""
        },
        {
            "name": "images",
            "baseName": "images",
            "type": "Array<IoK8sApiCoreV1ContainerImage>",
            "format": ""
        },
        {
            "name": "nodeInfo",
            "baseName": "nodeInfo",
            "type": "IoK8sApiCoreV1NodeSystemInfo",
            "format": ""
        },
        {
            "name": "phase",
            "baseName": "phase",
            "type": "string",
            "format": ""
        },
        {
            "name": "runtimeHandlers",
            "baseName": "runtimeHandlers",
            "type": "Array<IoK8sApiCoreV1NodeRuntimeHandler>",
            "format": ""
        },
        {
            "name": "volumesAttached",
            "baseName": "volumesAttached",
            "type": "Array<IoK8sApiCoreV1AttachedVolume>",
            "format": ""
        },
        {
            "name": "volumesInUse",
            "baseName": "volumesInUse",
            "type": "Array<string>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return IoK8sApiCoreV1NodeStatus.attributeTypeMap;
    }

    public constructor() {
    }
}
