/**
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: unversioned
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { IoK8sApiAdmissionregistrationV1alpha1TypeChecking } from '../models/IoK8sApiAdmissionregistrationV1alpha1TypeChecking';
import { IoK8sApimachineryPkgApisMetaV1Condition } from '../models/IoK8sApimachineryPkgApisMetaV1Condition';
import { HttpFile } from '../http/http';

/**
* ValidatingAdmissionPolicyStatus represents the status of a ValidatingAdmissionPolicy.
*/
export class IoK8sApiAdmissionregistrationV1alpha1ValidatingAdmissionPolicyStatus {
    /**
    * The conditions represent the latest available observations of a policy\'s current state.
    */
    'conditions'?: Array<IoK8sApimachineryPkgApisMetaV1Condition>;
    /**
    * The generation observed by the controller.
    */
    'observedGeneration'?: number;
    'typeChecking'?: IoK8sApiAdmissionregistrationV1alpha1TypeChecking;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "conditions",
            "baseName": "conditions",
            "type": "Array<IoK8sApimachineryPkgApisMetaV1Condition>",
            "format": ""
        },
        {
            "name": "observedGeneration",
            "baseName": "observedGeneration",
            "type": "number",
            "format": "int64"
        },
        {
            "name": "typeChecking",
            "baseName": "typeChecking",
            "type": "IoK8sApiAdmissionregistrationV1alpha1TypeChecking",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return IoK8sApiAdmissionregistrationV1alpha1ValidatingAdmissionPolicyStatus.attributeTypeMap;
    }

    public constructor() {
    }
}
