/**
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: unversioned
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { IoK8sApiFlowcontrolV1GroupSubject } from '../models/IoK8sApiFlowcontrolV1GroupSubject';
import { IoK8sApiFlowcontrolV1ServiceAccountSubject } from '../models/IoK8sApiFlowcontrolV1ServiceAccountSubject';
import { IoK8sApiFlowcontrolV1UserSubject } from '../models/IoK8sApiFlowcontrolV1UserSubject';
import { HttpFile } from '../http/http';

/**
* Subject matches the originator of a request, as identified by the request authentication system. There are three ways of matching an originator; by user, group, or service account.
*/
export class IoK8sApiFlowcontrolV1Subject {
    'group'?: IoK8sApiFlowcontrolV1GroupSubject;
    /**
    * `kind` indicates which one of the other fields is non-empty. Required
    */
    'kind': string;
    'serviceAccount'?: IoK8sApiFlowcontrolV1ServiceAccountSubject;
    'user'?: IoK8sApiFlowcontrolV1UserSubject;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "group",
            "baseName": "group",
            "type": "IoK8sApiFlowcontrolV1GroupSubject",
            "format": ""
        },
        {
            "name": "kind",
            "baseName": "kind",
            "type": "string",
            "format": ""
        },
        {
            "name": "serviceAccount",
            "baseName": "serviceAccount",
            "type": "IoK8sApiFlowcontrolV1ServiceAccountSubject",
            "format": ""
        },
        {
            "name": "user",
            "baseName": "user",
            "type": "IoK8sApiFlowcontrolV1UserSubject",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return IoK8sApiFlowcontrolV1Subject.attributeTypeMap;
    }

    public constructor() {
    }
}
