/**
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: unversioned
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { IoK8sApiAdmissionregistrationV1alpha1ExpressionWarning } from '../models/IoK8sApiAdmissionregistrationV1alpha1ExpressionWarning';
import { HttpFile } from '../http/http';

/**
* TypeChecking contains results of type checking the expressions in the ValidatingAdmissionPolicy
*/
export class IoK8sApiAdmissionregistrationV1alpha1TypeChecking {
    /**
    * The type checking warnings for each expression.
    */
    'expressionWarnings'?: Array<IoK8sApiAdmissionregistrationV1alpha1ExpressionWarning>;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "expressionWarnings",
            "baseName": "expressionWarnings",
            "type": "Array<IoK8sApiAdmissionregistrationV1alpha1ExpressionWarning>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return IoK8sApiAdmissionregistrationV1alpha1TypeChecking.attributeTypeMap;
    }

    public constructor() {
    }
}
