/**
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: unversioned
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { IoK8sApiResourceV1alpha3DeviceAttribute } from '../models/IoK8sApiResourceV1alpha3DeviceAttribute';
import { HttpFile } from '../http/http';

/**
* BasicDevice defines one device instance.
*/
export class IoK8sApiResourceV1alpha3BasicDevice {
    /**
    * Attributes defines the set of attributes for this device. The name of each attribute must be unique in that set.  The maximum number of attributes and capacities combined is 32.
    */
    'attributes'?: { [key: string]: IoK8sApiResourceV1alpha3DeviceAttribute; };
    /**
    * Capacity defines the set of capacities for this device. The name of each capacity must be unique in that set.  The maximum number of attributes and capacities combined is 32.
    */
    'capacity'?: { [key: string]: string; };

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "attributes",
            "baseName": "attributes",
            "type": "{ [key: string]: IoK8sApiResourceV1alpha3DeviceAttribute; }",
            "format": ""
        },
        {
            "name": "capacity",
            "baseName": "capacity",
            "type": "{ [key: string]: string; }",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return IoK8sApiResourceV1alpha3BasicDevice.attributeTypeMap;
    }

    public constructor() {
    }
}
