/**
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: unversioned
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { IoK8sApiFlowcontrolV1PriorityLevelConfigurationCondition } from '../models/IoK8sApiFlowcontrolV1PriorityLevelConfigurationCondition';
import { HttpFile } from '../http/http';

/**
* PriorityLevelConfigurationStatus represents the current state of a \"request-priority\".
*/
export class IoK8sApiFlowcontrolV1PriorityLevelConfigurationStatus {
    /**
    * `conditions` is the current state of \"request-priority\".
    */
    'conditions'?: Array<IoK8sApiFlowcontrolV1PriorityLevelConfigurationCondition>;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "conditions",
            "baseName": "conditions",
            "type": "Array<IoK8sApiFlowcontrolV1PriorityLevelConfigurationCondition>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return IoK8sApiFlowcontrolV1PriorityLevelConfigurationStatus.attributeTypeMap;
    }

    public constructor() {
    }
}
