/**
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: unversioned
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { IoK8sApiNetworkingV1IngressLoadBalancerStatus } from '../models/IoK8sApiNetworkingV1IngressLoadBalancerStatus';
import { HttpFile } from '../http/http';

/**
* IngressStatus describe the current state of the Ingress.
*/
export class IoK8sApiNetworkingV1IngressStatus {
    'loadBalancer'?: IoK8sApiNetworkingV1IngressLoadBalancerStatus;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "loadBalancer",
            "baseName": "loadBalancer",
            "type": "IoK8sApiNetworkingV1IngressLoadBalancerStatus",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return IoK8sApiNetworkingV1IngressStatus.attributeTypeMap;
    }

    public constructor() {
    }
}
