/**
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: unversioned
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { IoK8sApiNetworkingV1beta1ParentReference } from '../models/IoK8sApiNetworkingV1beta1ParentReference';
import { HttpFile } from '../http/http';

/**
* IPAddressSpec describe the attributes in an IP Address.
*/
export class IoK8sApiNetworkingV1beta1IPAddressSpec {
    'parentRef': IoK8sApiNetworkingV1beta1ParentReference;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "parentRef",
            "baseName": "parentRef",
            "type": "IoK8sApiNetworkingV1beta1ParentReference",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return IoK8sApiNetworkingV1beta1IPAddressSpec.attributeTypeMap;
    }

    public constructor() {
    }
}
