/**
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: unversioned
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { IoK8sApiResourceV1alpha3DeviceClaimConfiguration } from '../models/IoK8sApiResourceV1alpha3DeviceClaimConfiguration';
import { IoK8sApiResourceV1alpha3DeviceConstraint } from '../models/IoK8sApiResourceV1alpha3DeviceConstraint';
import { IoK8sApiResourceV1alpha3DeviceRequest } from '../models/IoK8sApiResourceV1alpha3DeviceRequest';
import { HttpFile } from '../http/http';

/**
* DeviceClaim defines how to request devices with a ResourceClaim.
*/
export class IoK8sApiResourceV1alpha3DeviceClaim {
    /**
    * This field holds configuration for multiple potential drivers which could satisfy requests in this claim. It is ignored while allocating the claim.
    */
    'config'?: Array<IoK8sApiResourceV1alpha3DeviceClaimConfiguration>;
    /**
    * These constraints must be satisfied by the set of devices that get allocated for the claim.
    */
    'constraints'?: Array<IoK8sApiResourceV1alpha3DeviceConstraint>;
    /**
    * Requests represent individual requests for distinct devices which must all be satisfied. If empty, nothing needs to be allocated.
    */
    'requests'?: Array<IoK8sApiResourceV1alpha3DeviceRequest>;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "config",
            "baseName": "config",
            "type": "Array<IoK8sApiResourceV1alpha3DeviceClaimConfiguration>",
            "format": ""
        },
        {
            "name": "constraints",
            "baseName": "constraints",
            "type": "Array<IoK8sApiResourceV1alpha3DeviceConstraint>",
            "format": ""
        },
        {
            "name": "requests",
            "baseName": "requests",
            "type": "Array<IoK8sApiResourceV1alpha3DeviceRequest>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return IoK8sApiResourceV1alpha3DeviceClaim.attributeTypeMap;
    }

    public constructor() {
    }
}
